spring.application.name=REST_API_FRAUD
server.port=8082
spring.jpa.show-sql=true
spring.profiles.active=JDBC
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.sql.init.mode=always
